const KEY='edusupport_tickets_v1';
const staff=['Anita Nair','Rahul Menon','Priya Shah','Arjun Kumar','Unassigned'];
const categories=['Fees','Attendance','ID Card','Documents','Certificates','Other'];
const statuses=['Open','In Progress','Pending','Resolved'];
const priorities=['Low','Medium','High','Critical'];
function seed(){return [
{id:'EDU-1001',student:'Aisha Rahman',roll:'CS24-041',category:'Fees',subject:'Installment payment not reflected',description:'Paid the second installment yesterday but the portal still shows an outstanding amount.',priority:'High',status:'Open',assignee:'Anita Nair',pendingReason:'',resolutionNotes:'',created:Date.now()-1000*60*60*30,sla:24,activities:[{by:'System',text:'Ticket created',at:Date.now()-1000*60*60*30}]},
{id:'EDU-1002',student:'Vivek S',roll:'EC23-118',category:'ID Card',subject:'ID card correction',description:'Department name is incorrect on my ID card.',priority:'Medium',status:'In Progress',assignee:'Rahul Menon',pendingReason:'',resolutionNotes:'',created:Date.now()-1000*60*60*8,sla:24,activities:[{by:'System',text:'Ticket created',at:Date.now()-1000*60*60*8},{by:'Rahul Menon',text:'Assigned and marked In Progress',at:Date.now()-1000*60*60*6}]},
{id:'EDU-1003',student:'Neha Joseph',roll:'BA23-077',category:'Documents',subject:'Bonafide certificate request',description:'Need a bonafide certificate for a scholarship application.',priority:'Low',status:'Pending',assignee:'Priya Shah',pendingReason:'Waiting for supporting document',resolutionNotes:'',created:Date.now()-1000*60*60*3,sla:48,activities:[{by:'System',text:'Ticket created',at:Date.now()-1000*60*60*3},{by:'Priya Shah',text:'Waiting for supporting document',at:Date.now()-1000*60*60*2}]},
{id:'EDU-1004',student:'Mohammed Irfan',roll:'ME22-031',category:'Attendance',subject:'Attendance correction request',description:'Attendance for the lab on Monday is missing.',priority:'Critical',status:'Resolved',assignee:'Arjun Kumar',pendingReason:'',resolutionNotes:'Attendance verified with faculty and corrected.',created:Date.now()-1000*60*60*26,sla:24,resolvedAt:Date.now()-1000*60*30,activities:[{by:'System',text:'Ticket created',at:Date.now()-1000*60*60*26},{by:'Arjun Kumar',text:'Attendance verified with faculty and corrected',at:Date.now()-1000*60*30}]}
]}
let tickets=JSON.parse(localStorage.getItem(KEY)||'null')||seed();
function save(){localStorage.setItem(KEY,JSON.stringify(tickets))}
function esc(s=''){return s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function hoursOld(t){return (Date.now()-t.created)/36e5}
function overdue(t){return t.status!=='Resolved' && hoursOld(t)>t.sla}
function age(t){let h=Math.floor(hoursOld(t));return h<1?'<1h':h<24?h+'h':Math.floor(h/24)+'d '+h%24+'h'}
function fmt(ts){return new Date(ts).toLocaleString('en-IN',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'})}
function statusClass(s){return 'status-'+s.toLowerCase().replace(' ','-')}
function priorityClass(p){return 'priority-'+p.toLowerCase()}
function toast(msg){let x=document.getElementById('toast');x.textContent=msg;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2200)}
function navigate(view){document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===view));document.querySelectorAll('.view').forEach(v=>v.classList.add('hidden'));document.getElementById(view+'View').classList.remove('hidden');let titles={dashboard:['Support Dashboard','Management visibility across student requests'],tickets:['Ticket Management','Own, prioritize, process and resolve requests'],new:['Create Support Ticket','Capture a new student request']};document.getElementById('pageTitle').textContent=titles[view][0];document.getElementById('pageSubtitle').textContent=titles[view][1];render(view)}
function renderDashboard(){let total=tickets.length,open=tickets.filter(t=>t.status==='Open').length,pending=tickets.filter(t=>t.status==='Pending').length,res=tickets.filter(t=>t.status==='Resolved').length,late=tickets.filter(overdue).length;
let cats=categories.map(c=>[c,tickets.filter(t=>t.category===c).length]);let max=Math.max(1,...cats.map(x=>x[1]));
document.getElementById('dashboardView').innerHTML=`<div class="cards"><div class="card"><div class="label">Total tickets</div><div class="metric">${total}</div><div class="small">All requests</div></div><div class="card"><div class="label">Open</div><div class="metric">${open}</div><div class="small">Awaiting action</div></div><div class="card"><div class="label">Pending</div><div class="metric">${pending}</div><div class="small">Waiting on action</div></div><div class="card"><div class="label">SLA breached</div><div class="metric ${late?'danger':''}">${late}</div><div class="small">Needs escalation</div></div></div>
<div class="grid2"><div class="panel"><h3>Requests by category</h3>${cats.map(([c,n])=>`<div class="bar-row"><span>${c}</span><div class="bar"><i style="width:${n/max*100}%"></i></div><b>${n}</b></div>`).join('')}</div><div class="panel"><h3>Management snapshot</h3><div class="recent-list"><div class="recent"><span>Resolution rate</span><b>${total?Math.round(res/total*100):0}%</b></div><div class="recent"><span>High / Critical</span><b>${tickets.filter(t=>['High','Critical'].includes(t.priority)).length}</b></div><div class="recent"><span>Unassigned</span><b>${tickets.filter(t=>t.assignee==='Unassigned').length}</b></div><div class="recent"><span>Resolved</span><b class="success">${res}</b></div></div></div></div>
<div class="panel" style="margin-top:18px"><h3>Recent activity</h3><div class="recent-list">${tickets.slice().sort((a,b)=>b.created-a.created).slice(0,5).map(t=>`<div class="recent"><div><span class="ticket-id" onclick="openTicket('${t.id}')">${t.id}</span> — ${esc(t.subject)}<div class="small">${esc(t.student)} · ${esc(t.assignee)}</div></div><span class="badge ${statusClass(t.status)}">${t.status}</span></div>`).join('')}</div></div>`}
function renderTickets(){document.getElementById('ticketsView').innerHTML=`<div class="toolbar"><input id="search" class="input" placeholder="Search ticket, student or subject"><select id="statusFilter" class="select"><option value="">All statuses</option>${statuses.map(s=>`<option>${s}</option>`).join('')}</select><select id="priorityFilter" class="select"><option value="">All priorities</option>${priorities.map(p=>`<option>${p}</option>`).join('')}</select><select id="categoryFilter" class="select"><option value="">All categories</option>${categories.map(c=>`<option>${c}</option>`).join('')}</select></div><div class="panel table-wrap"><table class="ticket-table"><thead><tr><th>Ticket</th><th>Student</th><th>Category</th><th>Priority</th><th>Status</th><th>Owner</th><th>Age / SLA</th></tr></thead><tbody id="ticketRows"></tbody></table></div>`;['search','statusFilter','priorityFilter','categoryFilter'].forEach(id=>document.getElementById(id).addEventListener('input',filterTickets));filterTickets()}
function filterTickets(){let q=document.getElementById('search').value.toLowerCase(),sf=document.getElementById('statusFilter').value,pf=document.getElementById('priorityFilter').value,cf=document.getElementById('categoryFilter').value;let arr=tickets.filter(t=>(!q||[t.id,t.student,t.subject,t.roll].join(' ').toLowerCase().includes(q))&&(!sf||t.status===sf)&&(!pf||t.priority===pf)&&(!cf||t.category===cf));document.getElementById('ticketRows').innerHTML=arr.length?arr.map(t=>`<tr><td><span class="ticket-id" onclick="openTicket('${t.id}')">${t.id}</span><div class="small">${esc(t.subject)}</div></td><td>${esc(t.student)}<div class="small">${esc(t.roll)}</div></td><td>${esc(t.category)}</td><td><span class="badge ${priorityClass(t.priority)}">${t.priority}</span></td><td><span class="badge ${statusClass(t.status)}">${t.status}</span></td><td>${esc(t.assignee)}</td><td class="${overdue(t)?'overdue':''}">${age(t)} / ${t.sla}h${overdue(t)?' · BREACHED':''}</td></tr>`).join(''):`<tr><td colspan="7" class="empty">No matching tickets</td></tr>`}
function renderNew(){document.getElementById('newView').innerHTML=`<div class="panel"><form id="ticketForm"><div class="form-grid"><div class="field"><label>Student name *</label><input required name="student" class="input" style="width:100%" placeholder="e.g. Aisha Rahman"></div><div class="field"><label>Student ID *</label><input required name="roll" class="input" style="width:100%" placeholder="e.g. CS24-041"></div><div class="field"><label>Category *</label><select required name="category" class="select" style="width:100%">${categories.map(c=>`<option>${c}</option>`).join('')}</select></div><div class="field"><label>Priority *</label><select name="priority" class="select" style="width:100%">${priorities.map(p=>`<option ${p==='Medium'?'selected':''}>${p}</option>`).join('')}</select></div><div class="field full"><label>Subject *</label><input required name="subject" class="input" style="width:100%" placeholder="Short description of the request"></div><div class="field full"><label>Description *</label><textarea required name="description" class="textarea" placeholder="Provide enough detail for staff to process the request"></textarea></div><div class="field"><label>Assign owner</label><select name="assignee" class="select" style="width:100%">${staff.map(s=>`<option>${s}</option>`).join('')}</select></div><div class="field"><label>SLA target</label><select name="sla" class="select" style="width:100%"><option value="8">8 hours — Critical</option><option value="24" selected>24 hours — Standard</option><option value="48">48 hours — Low</option></select></div></div><div class="form-actions"><button type="button" class="secondary" onclick="navigate('dashboard')">Cancel</button><button class="primary">Create ticket</button></div></form></div>`;document.getElementById('ticketForm').onsubmit=createTicket}
function createTicket(e){e.preventDefault();let f=new FormData(e.target),id='EDU-'+(1001+tickets.length+Math.floor(Math.random()*50));let t={id,student:f.get('student'),roll:f.get('roll'),category:f.get('category'),subject:f.get('subject'),description:f.get('description'),priority:f.get('priority'),status:'Open',assignee:f.get('assignee'),pendingReason:'',resolutionNotes:'',created:Date.now(),sla:Number(f.get('sla')),activities:[{by:'System',text:'Ticket created',at:Date.now()}]};tickets.unshift(t);save();toast(id+' created successfully');navigate('tickets')}
function openTicket(id){let t=tickets.find(x=>x.id===id);if(!t)return;document.getElementById('modalRoot').innerHTML=`<div class="modal-bg" onclick="if(event.target===this)closeModal()"><div class="modal"><div class="modal-head"><div><span class="ticket-id">${t.id}</span><h2 style="margin:7px 0 3px;font-size:20px">${esc(t.subject)}</h2><div class="small">${esc(t.student)} · ${esc(t.roll)}</div></div><button class="close" onclick="closeModal()">×</button></div><div class="detail-grid"><div class="detail"><b>CATEGORY</b>${esc(t.category)}</div><div class="detail"><b>AGE / SLA</b><span class="${overdue(t)?'overdue':''}">${age(t)} / ${t.sla}h ${overdue(t)?'— BREACHED':''}</span></div><div class="detail"><b>PRIORITY</b><select id="mPriority" class="select">${priorities.map(p=>`<option ${p===t.priority?'selected':''}>${p}</option>`).join('')}</select></div><div class="detail"><b>STATUS</b><select id="mStatus" class="select">${statuses.map(s=>`<option ${s===t.status?'selected':''}>${s}</option>`).join('')}</select></div><div class="detail"><b>OWNER</b><select id="mOwner" class="select">${staff.map(s=>`<option ${s===t.assignee?'selected':''}>${s}</option>`).join('')}</select></div><div class="detail"><b>CREATED</b>${fmt(t.created)}</div></div><div class="panel" style="background:#f8fafc;margin-bottom:15px"><b style="font-size:12px">REQUEST</b><p style="font-size:13px;line-height:1.5;margin-bottom:0">${esc(t.description)}</p></div><div class="panel"><h3>Workflow details</h3><div class="field"><label>Pending reason</label><select id="mPending" class="select" style="width:100%"><option value="">Not pending</option><option ${t.pendingReason==='Waiting for student'?'selected':''}>Waiting for student</option><option ${t.pendingReason==='Waiting for faculty'?'selected':''}>Waiting for faculty</option><option ${t.pendingReason==='Waiting for finance'?'selected':''}>Waiting for finance</option><option ${t.pendingReason==='Waiting for document'?'selected':''}>Waiting for document</option><option ${t.pendingReason==='Other'?'selected':''}>Other</option></select></div><div class="field" style="margin-top:10px"><label>Resolution notes</label><textarea id="mResolution" class="textarea" placeholder="Record what was done to resolve the request">${esc(t.resolutionNotes||'')}</textarea></div></div><div class="panel"><h3>Activity history</h3>${t.activities.slice().reverse().map(a=>`<div class="activity"><strong>${esc(a.by)}</strong><p>${esc(a.text)} · ${fmt(a.at)}</p></div>`).join('')}</div><div class="form-actions"><button class="secondary" onclick="escalate('${t.id}')">${overdue(t)?'Escalation logged':'Escalate'}</button><button class="primary" onclick="saveTicketChanges('${t.id}')">Save changes</button></div></div></div>`}
function saveTicketChanges(id){let t=tickets.find(x=>x.id===id),old={status:t.status,priority:t.priority,assignee:t.assignee,pendingReason:t.pendingReason||'',resolutionNotes:t.resolutionNotes||''};let ns=document.getElementById('mStatus').value,np=document.getElementById('mPriority').value,no=document.getElementById('mOwner').value,pr=document.getElementById('mPending').value,rn=document.getElementById('mResolution').value.trim();if(ns!==old.status)t.activities.push({by:no||'Staff',text:`Status changed from ${old.status} to ${ns}`,at:Date.now()});if(np!==old.priority)t.activities.push({by:no||'Staff',text:`Priority changed from ${old.priority} to ${np}`,at:Date.now()});if(no!==old.assignee)t.activities.push({by:no||'Staff',text:`Ownership changed from ${old.assignee} to ${no}`,at:Date.now()});if(pr!==old.pendingReason)t.activities.push({by:no||'Staff',text:pr?`Pending reason set to: ${pr}`:'Pending reason cleared',at:Date.now()});if(rn!==old.resolutionNotes&&rn)t.activities.push({by:no||'Staff',text:'Resolution notes updated',at:Date.now()});t.status=ns;t.priority=np;t.assignee=no;t.pendingReason=pr;t.resolutionNotes=rn;if(ns==='Resolved'&&!t.resolvedAt)t.resolvedAt=Date.now();save();closeModal();render('tickets');toast('Ticket updated')}
function escalate(id){let t=tickets.find(x=>x.id===id);t.activities.push({by:'System',text:'Ticket escalated for management review',at:Date.now()});save();openTicket(id);toast('Escalation recorded')}
function closeModal(){document.getElementById('modalRoot').innerHTML=''}
function render(v){if(v==='dashboard')renderDashboard();if(v==='tickets')renderTickets();if(v==='new')renderNew()}
document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>navigate(b.dataset.view));document.getElementById('topNew').onclick=()=>navigate('new');navigate('dashboard');setInterval(()=>{if(!document.getElementById('dashboardView').classList.contains('hidden'))renderDashboard()},60000);
